#Makefile

CC = gcc
CFLAGS = -Wall -Wextra -g

EXE = mainpop

all: ${EXE}

mainpop: mainpop.o population.o attraction.o


.PHONY: clean

clean:
	${RM} ${EXE} mainpop.o population.o attraction.o

#END
